import os

base = r'C:\Users\mycry\games\AgeOfShadows'

gamescene_content = (
    "import React, { useEffect, useRef } from 'react';\n"
    "import * as THREE from 'three';\n"
    "import { createEnvironment } from './modules/Environment';\n"
    "import { createHuman } from './modules/Human';\n"
    "import { createTree } from './modules/Tree';\n"
    "import { createUI } from './modules/UI';\n"
    "import { createControls } from './modules/Controls.jsx';\n"
    "import { createTownCenter } from './modules/Building';\n"
    "import { createChicken, createDeer } from './modules/Animal';\n"
    "import { createStone } from './modules/Stone';\n"
    "import { createGold } from './modules/Gold';\n"
    "export default function GameScene({ playerId, gameState }) {\n"
    "  const containerRef = useRef(null);\n"
    "  useEffect(() => {\n"
    "    if (!containerRef.current) return;\n"
    "    const scene = new THREE.Scene();\n"
    "    const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);\n"
    "    camera.position.set(0, 25, 35);\n"
    "    camera.lookAt(0, 0, 0);\n"
    "    const renderer = new THREE.WebGLRenderer({ antialias: true });\n"
    "    renderer.setSize(window.innerWidth, window.innerHeight);\n"
    "    renderer.shadowMap.enabled = true;\n"
    "    renderer.shadowMap.type = THREE.PCFShadowMap;\n"
    "    containerRef.current.appendChild(renderer.domElement);\n"
    "    const env = createEnvironment(scene);\n"
    "    const ui = createUI(playerId, gameState);\n"
    "    const resources = { wood: 10000, food: 10000, water: 10000, gold: 10000, stone: 10000 };\n"
    "    const world = { camera, units: [], trees: [], buildings: [], animals: [], stones: [], golds: [], resources, ui, pondPosition: env.pondPosition };\n"
    "    world.units.push(createHuman(scene, { x: -8, y: 0, z: 8 }, { team: 'red' }));\n"
    "    world.units.push(createHuman(scene, { x: 8, y: 0, z: 8 }, { team: 'blue' }));\n"
    "    const usedSpots = [];\n"
    "    function isTooClose(x, z, minDist) { return usedSpots.some((s) => Math.sqrt((x-s.x)**2+(z-s.z)**2) < minDist); }\n"
    "    function addSpot(x, z) { usedSpots.push({ x, z }); }\n"
    "    let attempts = 0;\n"
    "    while (world.trees.length < 20 && attempts < 300) {\n"
    "      attempts++;\n"
    "      const x = (Math.random()-0.5)*120; const z = (Math.random()-0.5)*120;\n"
    "      if (Math.sqrt(x*x+z*z) < 12) continue;\n"
    "      if (isTooClose(x, z, 5)) continue;\n"
    "      addSpot(x, z); world.trees.push(createTree(scene, { x, y:0, z }));\n"
    "    }\n"
    "    attempts = 0;\n"
    "    while (world.stones.length < 8 && attempts < 300) {\n"
    "      attempts++;\n"
    "      const x = (Math.random()-0.5)*120; const z = (Math.random()-0.5)*120;\n"
    "      if (Math.sqrt(x*x+z*z) < 15) continue;\n"
    "      if (isTooClose(x, z, 8)) continue;\n"
    "      addSpot(x, z); world.stones.push(createStone(scene, { x, y:0, z }));\n"
    "    }\n"
    "    attempts = 0;\n"
    "    while (world.golds.length < 4 && attempts < 300) {\n"
    "      attempts++;\n"
    "      const angle = Math.random()*Math.PI*2;\n"
    "      const r = 15 + Math.random()*30;\n"
    "      const x = Math.cos(angle)*r; const z = Math.sin(angle)*r;\n"
    "      if (isTooClose(x, z, 10)) continue;\n"
    "      addSpot(x, z); world.golds.push(createGold(scene, { x, y:0, z }));\n"
    "    }\n"
    "    world.golds.push(createGold(scene, { x: 5, y:0, z: 5 }));\n"
    "    const startTC = createTownCenter(scene, false);\n"
    "    startTC.setPosition(0, 0); startTC.place(); world.buildings.push(startTC);\n"
    "    world.animals.push(createChicken(scene, { x:6, y:0, z:6 }));\n"
    "    world.animals.push(createChicken(scene, { x:-6, y:0, z:6 }));\n"
    "    world.animals.push(createChicken(scene, { x:6, y:0, z:-6 }));\n"
    "    world.animals.push(createChicken(scene, { x:-6, y:0, z:-6 }));\n"
    "    world.animals.push(createChicken(scene, { x:0, y:0, z:8 }));\n"
    "    world.animals.push(createDeer(scene, { x:12, y:0, z:0 }));\n"
    "    world.animals.push(createDeer(scene, { x:-12, y:0, z:0 }));\n"
    "    world.animals.push(createDeer(scene, { x:0, y:0, z:12 }));\n"
    "    world.animals.push(createDeer(scene, { x:0, y:0, z:-12 }));\n"
    "    const { update, dispose } = createControls(camera, renderer, scene, world);\n"
    "    let last = performance.now(); let time = 0;\n"
    "    const animate = () => {\n"
    "      requestAnimationFrame(animate);\n"
    "      const now = performance.now(); let dt = (now-last)/1000; last = now;\n"
    "      if (dt > 0.1) dt = 0.1; time += dt;\n"
    "      update(time, dt);\n"
    "      if (env.waterUpdate) env.waterUpdate(dt);\n"
    "      world.trees.forEach((t) => t.update(dt));\n"
    "      world.stones.forEach((s) => s.update(dt));\n"
    "      world.golds.forEach((g) => g.update(dt));\n"
    "      world.animals.forEach((a) => a.update(dt, world));\n"
    "      world.units.forEach((u) => { u.update(dt, world); u.animate(dt); });\n"
    "      ui.setResources(resources);\n"
    "      renderer.render(scene, camera);\n"
    "    };\n"
    "    animate();\n"
    "    const handleResize = () => { camera.aspect = window.innerWidth/window.innerHeight; camera.updateProjectionMatrix(); renderer.setSize(window.innerWidth, window.innerHeight); };\n"
    "    window.addEventListener('resize', handleResize);\n"
    "    return () => {\n"
    "      window.removeEventListener('resize', handleResize); dispose();\n"
    "      if (containerRef.current && renderer.domElement.parentNode === containerRef.current) containerRef.current.removeChild(renderer.domElement);\n"
    "    };\n"
    "  }, [playerId]);\n"
    "  return React.createElement('div', { ref: containerRef, style: { width:'100%', height:'100vh', overflow:'hidden' } });\n"
    "}\n"
)

with open(base + r'\client\src\GameScene.js', 'w', encoding='utf-8') as f:
    f.write(gamescene_content)
print('Done!')